### ISSUE TITLE
[Vue warn]: Failed to mount component

### ISSUE THREAD

**Issue by nebaughman** [FranckFreiburger/vue-calendar-picker#11]
Thanks for this component; it looks really useful, but I cannot get it to work in a simple npm+webpack+vue project. Console gives this error:
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Calendar>
       <App> at src/App.vue
         <Root>
```

Sample project created with `vue init webpack calendar` (chose `Runtime  + Compiler` option for Vue).

This is the default `App.vue` created by the init script above, removing `HelloWorld` component (which works) for your `calendar` component:
```
<template>
  <div id="app">
    <calendar/>
  </div>
</template>

<script>
import {calendar} from 'vue-calendar-picker'

export default {
  name: 'app',
  components: {
    calendar: calendar
  }
}
</script>

<style>
</style>
```

Maybe I'm doing something wrong here? Any advice is most welcome.

**Comment by FranckFreiburger** [comment]
fixed in 2.0.0
