### ISSUE TITLE
Set/change current view date

### ISSUE THREAD

**Issue by Pistos** [FranckFreiburger/vue-calendar-picker#6]
I am using `calendarRange`, and am programmatically updating the selection, and that works just fine.  However, sometimes that selection is not visible in the current view (e.g. looking at June, and the selection is the first week of May).  How can I update the current month to go to, say, the start date of the selection?

I've tried this, but it doesn't work (only snippets shown, for brevity):

```
    <calendar-range                                                                                                                         
      :events="calendarEvents"                                                                                                              
      :selection="calendarSelection"                                                                                                        
      :initialCurrent="currentCalendarDate"                                                                                                 
    ></calendar-range>

    currentCalendarDate: function () {                                                                                                      
      return this.currentCalendarMoment.toDate()                                                                                            
    },

    this.currentCalendarMoment = moment('2017-05-01')
```

**Comment by AlexZhengs** [comment]
- there is  a errlog `Error in render function: "Error: Cannot find module './zh/index.js'."`

- I think the reason is here.  `‘src/mixin.js’`

- The specific code location is here

> default property

`locale:{` 

   `type:String,`

   `default: (navigator.language || navigator.userLanguage).substr(0,2).toUpperCase()`

   `validator: function(value) {
				return value === value.toUpperCase();
			}`

`}`
