### ISSUE TITLE
Cannot find module './zh/index.js

### ISSUE THREAD

**Issue by sevensung** [FranckFreiburger/vue-calendar-picker#7]
- there is  a errlog `Error in render function: "Error: Cannot find module './zh/index.js'."`

- I think the reason is here.  `‘src/mixin.js’`

- The specific code location is here

> default property

`locale:{` 

   `type:String,`

   `default: (navigator.language || navigator.userLanguage).substr(0,2).toUpperCase()`

   `validator: function(value) {
				return value === value.toUpperCase();
			}`

`}`

**Comment by FranckFreiburger** [comment]
Here is a list of supported locales: https://github.com/date-fns/date-fns/tree/master/src/locale
You should use zh-CN or zh-TW
